HangmanBundle\Game\ReadModel\LetterChosen:
  type: entity
  table: gameletterschosen
  fields:
          id:
              id: true
              type: integer
              unsigned: false
              nullable: false
              column: id
              generator:
                  strategy: IDENTITY
          gameId:
              type: string
              length: 50
              nullable: false
          letter:
              type: string
              length: 10
              nullable: false
          correctGuessed:
              type: boolean
              default: false
          misGuessed:
              type: boolean
              default: false
  lifecycleCallbacks: {}