HangmanBundle\Game\ReadModel\GameEnd:
  type: entity
  table: game_end
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
          strategy: IDENTITY
    gameId:
        type: string
        length: 50
        nullable: false
    status:
        type: integer
        length: 1
    timeExpanned:
        type: time
        nullable: false
  lifecycleCallbacks: {}