services:
  hangman.game.controller:
    class: Hangman\Bundle\Controller\GameController
    arguments:
      - @broadway.command_handling.command_bus
      - @broadway.uuid.generator
      - @form.factory
      - @router
      - @hangman.game.read_model_repository