HangmanBundle\Game\ReadModel\GameStatics:
  type: document
  table: gamesstatics
  embedded:
    LetterSaver:
      class: HangmanBundle\Models\LetterSaver
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
          strategy: IDENTITY
    gameId:
      type: string
      length: 50
      nullable: false
    letterWrongGuessed:
        type: Models\LetterSaver
        length: 255
        nullable: true
    letterCorrectlyGuessed:
        type: Models\LetterSaver
        length: 255
        nullable: true
    gameStatus:
      type: string
      length: 50
      nullable: false
    expanededTimeOnGame:
      type: datetime
      nullable: true
    gameStartTime:
      type: datetime
      nullable: true
    gameEndTime:
      type: datetime
      nullable: true