HangmanBundle\Game\ReadModel\GameStatics:
  type: entity
  table: gamesstatics
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
          strategy: IDENTITY
    gameId:
      type: string
      length: 50
      nullable: false
    letterWrongGuessed:
        type: string
        length: 255
        nullable: true
    letterCorrectlyGuessed:
        type: string
        length: 255
        nullable: true
    gameStatus:
      type: string
      length: 50
      nullable: false
    expanededTimeOnGame:
      type: string
      nullable: true
    gameStartTime:
      type: string
      nullable: true
    gameEndTime:
      type: string
      nullable: true