HangmanBundle\Game\ReadModel\Game:
    type: entity
    table: game
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id
            generator:
                strategy: IDENTITY
        gameId:
            type: string
            length: 50
            nullable: false
        word:
            type: string
            length: 50
            nullable: false
        letterWrongGuessed:
            type: string
            length: 255
            nullable: true
        letterCorrectlyGuessed:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {}