HangmanBundle\Game\ReadModel\GameStarted:
    type: entity
    table: gamesstarted
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id
            generator:
                strategy: IDENTITY
        gameId:
            type: string
            length: 50
            nullable: false
        word:
            type: string
            length: 50
            nullable: false
    lifecycleCallbacks: {}