services:
    hangman.controller.game:
        class: HangmanBundle\Controller\DefaultController
        arguments:
            - "@broadway.command_handling.command_bus"
            - "@broadway.uuid.generator"
            - "@form.factory"
            - "@router"
            - "@hangman.read_model_game_repository"

    hangman.controller.games_statics:
        class: HangmanBundle\Controller\GamesStaticsController
        arguments:
            - "@broadway.command_handling.command_bus"
            - "@broadway.uuid.generator"
            - "@form.factory"
            - "@router"
            - "@hangman.read_model_game_statics_repository"
            - 'HangmanBundle:Game\ReadModel\GameStarted'

    sim.read_model.repository.game:
        class: HangmanBundle\Game\ReadModel\Doctrine\DoctrineRepository
        arguments: [@doctrine.orm.entity_manager, "HangmanApplication:Game\Domain\Config\GameStarted"]

    hangman.services.messages:
        class: HangmanBundle\Services\MessagesService